version: '3'
services:
  web:
    container_name: go-monitoring
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7879:8055" # Ändere die Portzuweisung nach Bedarf